### ISSUE TITLE
https://prod.liveshare.vsengsaas.visualstudio.com/join?E95EE1780F3AA52019E4AC85A31BBE083708

### ISSUE THREAD

**Issue by moonformeli** [Min-92/algorithm#1]
https://prod.liveshare.vsengsaas.visualstudio.com/join?E95EE1780F3AA52019E4AC85A31BBE083708

**Comment by moonformeli** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?E95EE1780F3AA52019E4AC85A31BBE083708

**Comment by moonformeli** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?24698ABF6232C75B5B3B16256BC3085391B2

**Comment by moonformeli** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?47F19B604E3BF707602DCB3CCCD7E384CE5B

**Comment by Min-92** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?02D805D468057EA77B0ED864B6A2ADEDB5EE
